---
abstract: 'Simple prompting with validation hooks.'
author:
  - 'David Oswald <davido [@at] cpan [d.o.t] org>'
build_requires:
  Capture::Tiny: 0
  English: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.62
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Prompt-Hooked
no_index:
  directory:
    - t
    - inc
provides:
  IO::Prompt::Hooked:
    file: lib/IO/Prompt/Hooked.pm
    version: 0.08
requires:
  IO::Prompt::Tiny: 0.001
  Params::Smart: 0.08
  parent: 0.225
  perl: 5.006000
version: 0.08
